# Generated by Django 2.2 on 2019-12-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191214_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostlikes',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
